name: CD with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# github action이 읽을 수 있도록 수정 
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: "adopt"

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test
          
      - name: Docker build & push to docker repo
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.DOCKER_REPO }}/happybirthday .
          docker push ${{ secrets.DOCKER_REPO }}/happybirthday

	# 기존에 실행되는 컨테이너 모두 멈춤 
	# 서버에 접속하여 pull 한 후 실행 
        # docker-comppose에 작성해둔 컨테이너 백그라운드로 실행
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        id: deploy
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          envs: GITHUB_SHA
          script: |
            sudo docker rm -f $(docker ps -qa)
            sudo docker stop $(docker ps -a -q)
            sudo docker pull ${{ secrets.DOCKER_REPO }}/happybirthday
            sudo docker-compose up --build -d
            sudo docker image prune -f
